CREATE TABLE POLLS (
  ID BIGSERIAL PRIMARY KEY,
  QUESTION VARCHAR NOT NULL,
  SECURITY_TYPE VARCHAR
);

CREATE TABLE ANSWERS (
  ID BIGSERIAL PRIMARY KEY,
  POLL_ID INT8 NOT NULL REFERENCES POLLS (ID),
  RESPONSE VARCHAR NOT NULL,
  RANK INT8 NOT NULL,
  COUNT INT8 NOT NULL
);

CREATE TABLE IP_ADDRESSES (
  ID BIGSERIAL PRIMARY KEY,
  ANSWER_ID INT8 NOT NULL REFERENCES ANSWERS (ID),
  VALUE VARCHAR NOT NULL
);


INSERT INTO POLLS VALUES (123, 'Am I the best?', NULL);
INSERT INTO ANSWERS VALUES (999, 123, 'Yes', 1, 0);
INSERT INTO ANSWERS VALUES (9995, 123, 'No', 2, 0);

INSERT INTO POLLS VALUES (124, 'Am I not the best?', 'IpAddressCheck');
INSERT INTO ANSWERS VALUES (1000, 124, 'Yes', 1, 1);
INSERT INTO ANSWERS VALUES (1001, 124, 'No', 2, 0);
INSERT INTO IP_ADDRESSES VALUES (1, 1000, '0:0:0:0:0:0:0:1');
