CREATE TABLE POLLS (
  ID BIGSERIAL PRIMARY KEY,
  QUESTION VARCHAR NOT NULL
);

CREATE TABLE ANSWERS (
  ID BIGSERIAL PRIMARY KEY,
  POLL_ID INT8 NOT NULL REFERENCES POLLS (ID),
  RESPONSE VARCHAR NOT NULL,
  COUNT INT8 NOT NULL
);

INSERT INTO POLLS VALUES (123, 'Am I the best?');
INSERT INTO ANSWERS VALUES (999, 123, 'Yes', 0);
INSERT INTO ANSWERS VALUES (9995, 123, 'No', 0);

